---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: 3.11.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  targetNamespace: kube-system
  install:
    createNamespace: false
  upgrade:
    cleanupOnFail: true
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
